### ISSUE TITLE
Init - 프로젝트 세팅

### ISSUE THREAD

**Issue by jumining** [PetToothFairy/Client-iOS#1]
## What is this issue? 🚀
프로젝트 세팅 및 UI 초기 구현

## TODO 🏃‍♀️
- [x] 초기 프로젝트 세팅
- [x] UI 기초 구현
- [x] 이슈 템플릿 추가
